const type1 = [
  {
    id: "1",
    name: "Cản trở người thi hành công vụ",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "2",
    name: "Hỗ trợ đồng bọn, trợ giúp tội phạm",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "3",
    name: "Không giao nộp hung khí gây án",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "4",
    name: "Tàng trữ hoặc sử dụng Giáp trái phép",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "5",
    name: "Giả dạng, tự xưng là người nhà nước",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "6",
    name: "Gây rối trật tự công cộng",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "7",
    name: "Trộm cắp tài sản công dân",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "8",
    name: "Phá hoại tài sản nhà nước",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "9",
    name: "Sử dụng nấm đấm gây rối trật tự công cộng",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
  {
    id: "10",
    name: "Gây rối trước trụ sở cơ quan nhà nước",
    quantity: 1,
    isSelected: false,
    point: 20,
    type: 1,
  },
];

const type2 = [
  {
    id: "11",
    name: "Nhập cư trái phép",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "12",
    name: "Tàng trữ chất cấm trái phép (Cây thảo dược)",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "13",
    name: "Vu khống người khác",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "14",
    name: "Có lời lẽ xúc phạm đến danh dự, nhân phẩm người khác",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "15",
    name: "Sử dụng vũ khí thô sơ nơi công cộng",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "16",
    name: "Sử dụng vũ khí nóng nơi công cộng",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "17",
    name: "Lừa đảo, chiếm đoạt tài sản người khác",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "18",
    name: "Gây thương tích chưa nghiêm trọng cho người khác",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "19",
    name: "Chống đối người thi hành công vụ",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "20",
    name: "Xâm nhập trụ sở, nơi làm việc ban ngành nhà nước",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "21",
    name: "Xúc phạm Sĩ quan cảnh sát",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
  {
    id: "22",
    name: "Sử dụng phương tiện gây thương tích chưa nghiêm trọng",
    quantity: 1,
    isSelected: false,
    point: 30,
    type: 2,
  },
];

const type3 = [
  {
    id: "23",
    name: "Tấn công người khác gây thương tích nghiêm trọng",
    quantity: 1,
    isSelected: false,
    point: 60,
    type: 3,
  },
  {
    id: "24",
    name: "Mua bán vũ khí trái phép",
    quantity: 1,
    isSelected: false,
    point: 60,
    type: 3,
  },
  {
    id: "25",
    name: "Sử dụng vũ khí tấn công Quân đội",
    quantity: 1,
    isSelected: false,
    point: 60,
    type: 3,
  },
  {
    id: "26",
    name: "Sử dụng vũ khí tấn công Cảnh Sát",
    quantity: 1,
    isSelected: false,
    point: 60,
    type: 3,
  },
  {
    id: "27",
    name: "Sử dụng vũ khí tấn công Giảng viên Học viện",
    quantity: 1,
    isSelected: false,
    point: 60,
    type: 3,
  },
  {
    id: "28",
    name: "Sử dụng vũ khí tấn công Nhân viên MW",
    quantity: 1,
    isSelected: false,
    point: 60,
    type: 3,
  },
  {
    id: "29",
    name: "Sử dụng vũ khí tấn công FIB",
    quantity: 1,
    isSelected: false,
    point: 60,
    type: 3,
  },
  {
    id: "30",
    name: "Sử dụng phương tiện gây thương tích nghiêm trọng",
    quantity: 1,
    isSelected: false,
    point: 60,
    type: 3,
  },
];

const type4 = [
  {
    id: "31",
    name: "Tấn công Cán bộ cấp cao, Quản lý ban ngành thuộc Nhà nước",
    quantity: 1,
    isSelected: false,
    point: 120,
    type: 4,
  },
  {
    id: "32",
    name: "Tấn công Nhân viên Y Tế (EMS)",
    quantity: 1,
    isSelected: false,
    point: 120,
    type: 4,
  },
  {
    id: "33",
    name: "Có lời nói, hành động đe doạ Nhân viên Chính Phủ",
    quantity: 1,
    isSelected: false,
    point: 120,
    type: 4,
  },
  {
    id: "34",
    name: "Tấn công Nhân viên báo chí",
    quantity: 1,
    isSelected: false,
    point: 120,
    type: 4,
  },
];

const type5 = [
  {
    id: "35",
    name: "Bạo động thành phố",
    quantity: 1,
    isSelected: false,
    point: 200,
    type: 5,
  },
  {
    id: "36",
    name: "Lợi dụng quyền ra toà để bỏ trốn hoặc bỏ trốn trong thời gian được tại ngoại chờ ra toà",
    quantity: 1,
    isSelected: false,
    point: 200,
    type: 5,
  },
  {
    id: "37",
    name: "Tấn công Trụ sở, nơi làm việc của Ban ngành Nhà nước",
    quantity: 1,
    isSelected: false,
    point: 200,
    type: 5,
  },
  {
    id: "38",
    name: "Tấn công Thống Đốc, Phó Thống Đốc, Nhân viên Chính Phủ",
    quantity: 1,
    isSelected: false,
    point: 200,
    type: 5,
  },
  {
    id: "39",
    name: "Đột nhập Trụ sở làm việc Học Viện Quốc Gia",
    quantity: 1,
    isSelected: false,
    point: 200,
    type: 5,
  },
  {
    id: "40",
    name: "Đột nhập Trụ sở làm việc Nhà Tù (hoặc Quân khu)",
    quantity: 1,
    isSelected: false,
    point: 200,
    type: 5,
  },
];

export { type1, type2, type3, type4, type5 };
